package pojos;
// Generated 16/06/2012 12:08:15 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Cita generated by hbm2java
 */
public class Cita  implements java.io.Serializable {


     private Integer idCita;
     private DatosDoctor datosDoctor;
     private DatosPaciente datosPaciente;
     private String desCita;
     private Date fechaInicial;
     private Date fechaFinal;

    public Cita() {
    }

    public Cita(DatosDoctor datosDoctor, DatosPaciente datosPaciente, String desCita, Date fechaInicial, Date fechaFinal) {
       this.datosDoctor = datosDoctor;
       this.datosPaciente = datosPaciente;
       this.desCita = desCita;
       this.fechaInicial = fechaInicial;
       this.fechaFinal = fechaFinal;
    }
   
    public Integer getIdCita() {
        return this.idCita;
    }
    
    public void setIdCita(Integer idCita) {
        this.idCita = idCita;
    }
    public DatosDoctor getDatosDoctor() {
        return this.datosDoctor;
    }
    
    public void setDatosDoctor(DatosDoctor datosDoctor) {
        this.datosDoctor = datosDoctor;
    }
    public DatosPaciente getDatosPaciente() {
        return this.datosPaciente;
    }
    
    public void setDatosPaciente(DatosPaciente datosPaciente) {
        this.datosPaciente = datosPaciente;
    }
    public String getDesCita() {
        return this.desCita;
    }
    
    public void setDesCita(String desCita) {
        this.desCita = desCita;
    }
    public Date getFechaInicial() {
        return this.fechaInicial;
    }
    
    public void setFechaInicial(Date fechaInicial) {
        this.fechaInicial = fechaInicial;
    }
    public Date getFechaFinal() {
        return this.fechaFinal;
    }
    
    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }




}


