package pojos;
// Generated 16/05/2012 07:53:45 PM by Hibernate Tools 3.2.1.GA



/**
 * Configuracion generated by hbm2java
 */
public class Configuracion  implements java.io.Serializable , Comparable {


     private Integer id;
     private String descripcion;
     private String valor;

    public Configuracion() {
    }

    public Configuracion(String descripcion, String valor) {
       this.descripcion = descripcion;
       this.valor = valor;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }

    @Override
    public int compareTo(Object o) {
        Configuracion cast=(Configuracion) o;
        return this.id.compareTo(cast.id);
    }




}


