package pojos;
// Generated 24/05/2012 08:46:41 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * DatosDoctor generated by hbm2java
 */
public class DatosDoctor  implements java.io.Serializable {


     private Integer idDoctor;
     private String apePat;
     private String apeMat;
     private String nom;
     private String segNom;
     private String usu;
     private String pas;
     private Set consultas = new HashSet(0);
     private Set citas = new HashSet(0);

    public DatosDoctor() {
    }

    public DatosDoctor(String apePat, String apeMat, String nom, String segNom, String usu, String pas, Set consultas, Set citas) {
       this.apePat = apePat;
       this.apeMat = apeMat;
       this.nom = nom;
       this.segNom = segNom;
       this.usu = usu;
       this.pas = pas;
       this.consultas = consultas;
       this.citas = citas;
    }
   
    public Integer getIdDoctor() {
        return this.idDoctor;
    }
    
    public void setIdDoctor(Integer idDoctor) {
        this.idDoctor = idDoctor;
    }
    public String getApePat() {
        return this.apePat;
    }
    
    public void setApePat(String apePat) {
        this.apePat = apePat;
    }
    public String getApeMat() {
        return this.apeMat;
    }
    
    public void setApeMat(String apeMat) {
        this.apeMat = apeMat;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getSegNom() {
        return this.segNom;
    }
    
    public void setSegNom(String segNom) {
        this.segNom = segNom;
    }
    public String getUsu() {
        return this.usu;
    }
    
    public void setUsu(String usu) {
        this.usu = usu;
    }
    public String getPas() {
        return this.pas;
    }
    
    public void setPas(String pas) {
        this.pas = pas;
    }
    public Set getConsultas() {
        return this.consultas;
    }
    
    public void setConsultas(Set consultas) {
        this.consultas = consultas;
    }
    public Set getCitas() {
        return this.citas;
    }
    
    public void setCitas(Set citas) {
        this.citas = citas;
    }




}


