package pojos;
// Generated 16/05/2012 07:53:45 PM by Hibernate Tools 3.2.1.GA



/**
 * ExpedienteMatriz generated by hbm2java
 */
public class ExpedienteMatriz  implements java.io.Serializable {


     private Integer idMatriz;
     private DatosPaciente datosPaciente;
     private String obeMama;
     private String obePapa;
     private String obePac;
     private String diaMama;
     private String diaPapa;
     private String diaPac;
     private String hipMama;
     private String hipPapa;
     private String hipPac;
     private String triMama;
     private String triPapa;
     private String triPac;
     private String colMama;
     private String colPapa;
     private String colPac;
     private String aleMama;
     private String alePapa;
     private String alePac;
     private String tabMama;
     private String tabPapa;
     private String tabPac;
     private String alcMama;
     private String alcPapa;
     private String alcPac;
     private String mensMama;
     private String mensPapa;
     private String mensPac;
     private String cardMama;
     private String cardPapa;
     private String cardPac;
     private String estrePac;
     private String retLiqPac;
     private String varPac;

    public ExpedienteMatriz() {
    }

    public ExpedienteMatriz(DatosPaciente datosPaciente, String obeMama, String obePapa, String obePac, String diaMama, String diaPapa, String diaPac, String hipMama, String hipPapa, String hipPac, String triMama, String triPapa, String triPac, String colMama, String colPapa, String colPac, String aleMama, String alePapa, String alePac, String tabMama, String tabPapa, String tabPac, String alcMama, String alcPapa, String alcPac, String mensMama, String mensPapa, String mensPac, String cardMama, String cardPapa, String cardPac, String estrePac, String retLiqPac, String varPac) {
       this.datosPaciente = datosPaciente;
       this.obeMama = obeMama;
       this.obePapa = obePapa;
       this.obePac = obePac;
       this.diaMama = diaMama;
       this.diaPapa = diaPapa;
       this.diaPac = diaPac;
       this.hipMama = hipMama;
       this.hipPapa = hipPapa;
       this.hipPac = hipPac;
       this.triMama = triMama;
       this.triPapa = triPapa;
       this.triPac = triPac;
       this.colMama = colMama;
       this.colPapa = colPapa;
       this.colPac = colPac;
       this.aleMama = aleMama;
       this.alePapa = alePapa;
       this.alePac = alePac;
       this.tabMama = tabMama;
       this.tabPapa = tabPapa;
       this.tabPac = tabPac;
       this.alcMama = alcMama;
       this.alcPapa = alcPapa;
       this.alcPac = alcPac;
       this.mensMama = mensMama;
       this.mensPapa = mensPapa;
       this.mensPac = mensPac;
       this.cardMama = cardMama;
       this.cardPapa = cardPapa;
       this.cardPac = cardPac;
       this.estrePac = estrePac;
       this.retLiqPac = retLiqPac;
       this.varPac = varPac;
    }
   
    public Integer getIdMatriz() {
        return this.idMatriz;
    }
    
    public void setIdMatriz(Integer idMatriz) {
        this.idMatriz = idMatriz;
    }
    public DatosPaciente getDatosPaciente() {
        return this.datosPaciente;
    }
    
    public void setDatosPaciente(DatosPaciente datosPaciente) {
        this.datosPaciente = datosPaciente;
    }
    public String getObeMama() {
        return this.obeMama;
    }
    
    public void setObeMama(String obeMama) {
        this.obeMama = obeMama;
    }
    public String getObePapa() {
        return this.obePapa;
    }
    
    public void setObePapa(String obePapa) {
        this.obePapa = obePapa;
    }
    public String getObePac() {
        return this.obePac;
    }
    
    public void setObePac(String obePac) {
        this.obePac = obePac;
    }
    public String getDiaMama() {
        return this.diaMama;
    }
    
    public void setDiaMama(String diaMama) {
        this.diaMama = diaMama;
    }
    public String getDiaPapa() {
        return this.diaPapa;
    }
    
    public void setDiaPapa(String diaPapa) {
        this.diaPapa = diaPapa;
    }
    public String getDiaPac() {
        return this.diaPac;
    }
    
    public void setDiaPac(String diaPac) {
        this.diaPac = diaPac;
    }
    public String getHipMama() {
        return this.hipMama;
    }
    
    public void setHipMama(String hipMama) {
        this.hipMama = hipMama;
    }
    public String getHipPapa() {
        return this.hipPapa;
    }
    
    public void setHipPapa(String hipPapa) {
        this.hipPapa = hipPapa;
    }
    public String getHipPac() {
        return this.hipPac;
    }
    
    public void setHipPac(String hipPac) {
        this.hipPac = hipPac;
    }
    public String getTriMama() {
        return this.triMama;
    }
    
    public void setTriMama(String triMama) {
        this.triMama = triMama;
    }
    public String getTriPapa() {
        return this.triPapa;
    }
    
    public void setTriPapa(String triPapa) {
        this.triPapa = triPapa;
    }
    public String getTriPac() {
        return this.triPac;
    }
    
    public void setTriPac(String triPac) {
        this.triPac = triPac;
    }
    public String getColMama() {
        return this.colMama;
    }
    
    public void setColMama(String colMama) {
        this.colMama = colMama;
    }
    public String getColPapa() {
        return this.colPapa;
    }
    
    public void setColPapa(String colPapa) {
        this.colPapa = colPapa;
    }
    public String getColPac() {
        return this.colPac;
    }
    
    public void setColPac(String colPac) {
        this.colPac = colPac;
    }
    public String getAleMama() {
        return this.aleMama;
    }
    
    public void setAleMama(String aleMama) {
        this.aleMama = aleMama;
    }
    public String getAlePapa() {
        return this.alePapa;
    }
    
    public void setAlePapa(String alePapa) {
        this.alePapa = alePapa;
    }
    public String getAlePac() {
        return this.alePac;
    }
    
    public void setAlePac(String alePac) {
        this.alePac = alePac;
    }
    public String getTabMama() {
        return this.tabMama;
    }
    
    public void setTabMama(String tabMama) {
        this.tabMama = tabMama;
    }
    public String getTabPapa() {
        return this.tabPapa;
    }
    
    public void setTabPapa(String tabPapa) {
        this.tabPapa = tabPapa;
    }
    public String getTabPac() {
        return this.tabPac;
    }
    
    public void setTabPac(String tabPac) {
        this.tabPac = tabPac;
    }
    public String getAlcMama() {
        return this.alcMama;
    }
    
    public void setAlcMama(String alcMama) {
        this.alcMama = alcMama;
    }
    public String getAlcPapa() {
        return this.alcPapa;
    }
    
    public void setAlcPapa(String alcPapa) {
        this.alcPapa = alcPapa;
    }
    public String getAlcPac() {
        return this.alcPac;
    }
    
    public void setAlcPac(String alcPac) {
        this.alcPac = alcPac;
    }
    public String getMensMama() {
        return this.mensMama;
    }
    
    public void setMensMama(String mensMama) {
        this.mensMama = mensMama;
    }
    public String getMensPapa() {
        return this.mensPapa;
    }
    
    public void setMensPapa(String mensPapa) {
        this.mensPapa = mensPapa;
    }
    public String getMensPac() {
        return this.mensPac;
    }
    
    public void setMensPac(String mensPac) {
        this.mensPac = mensPac;
    }
    public String getCardMama() {
        return this.cardMama;
    }
    
    public void setCardMama(String cardMama) {
        this.cardMama = cardMama;
    }
    public String getCardPapa() {
        return this.cardPapa;
    }
    
    public void setCardPapa(String cardPapa) {
        this.cardPapa = cardPapa;
    }
    public String getCardPac() {
        return this.cardPac;
    }
    
    public void setCardPac(String cardPac) {
        this.cardPac = cardPac;
    }
    public String getEstrePac() {
        return this.estrePac;
    }
    
    public void setEstrePac(String estrePac) {
        this.estrePac = estrePac;
    }
    public String getRetLiqPac() {
        return this.retLiqPac;
    }
    
    public void setRetLiqPac(String retLiqPac) {
        this.retLiqPac = retLiqPac;
    }
    public String getVarPac() {
        return this.varPac;
    }
    
    public void setVarPac(String varPac) {
        this.varPac = varPac;
    }




}


