package pojos;
// Generated 25/06/2012 06:37:10 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ExpedienteComidas generated by hbm2java
 */
public class ExpedienteComidas  implements java.io.Serializable {


     private Integer idComidas;
     private DatosPaciente datosPaciente;
     private String desDesayuno;
     private String lugDesayuno;
     private String comeSoloDesayuno;
     private Date horaDesayuno;
     private String desComida;
     private String lugComida;
     private String comeSoloComida;
     private Date horaComida;
     private String desCena;
     private String lugCena;
     private String comeSoloCena;
     private Date horaCena;

    public ExpedienteComidas() {
    }

    public ExpedienteComidas(DatosPaciente datosPaciente, String desDesayuno, String lugDesayuno, String comeSoloDesayuno, Date horaDesayuno, String desComida, String lugComida, String comeSoloComida, Date horaComida, String desCena, String lugCena, String comeSoloCena, Date horaCena) {
       this.datosPaciente = datosPaciente;
       this.desDesayuno = desDesayuno;
       this.lugDesayuno = lugDesayuno;
       this.comeSoloDesayuno = comeSoloDesayuno;
       this.horaDesayuno = horaDesayuno;
       this.desComida = desComida;
       this.lugComida = lugComida;
       this.comeSoloComida = comeSoloComida;
       this.horaComida = horaComida;
       this.desCena = desCena;
       this.lugCena = lugCena;
       this.comeSoloCena = comeSoloCena;
       this.horaCena = horaCena;
    }
   
    public Integer getIdComidas() {
        return this.idComidas;
    }
    
    public void setIdComidas(Integer idComidas) {
        this.idComidas = idComidas;
    }
    public DatosPaciente getDatosPaciente() {
        return this.datosPaciente;
    }
    
    public void setDatosPaciente(DatosPaciente datosPaciente) {
        this.datosPaciente = datosPaciente;
    }
    public String getDesDesayuno() {
        return this.desDesayuno;
    }
    
    public void setDesDesayuno(String desDesayuno) {
        this.desDesayuno = desDesayuno;
    }
    public String getLugDesayuno() {
        return this.lugDesayuno;
    }
    
    public void setLugDesayuno(String lugDesayuno) {
        this.lugDesayuno = lugDesayuno;
    }
    public String getComeSoloDesayuno() {
        return this.comeSoloDesayuno;
    }
    
    public void setComeSoloDesayuno(String comeSoloDesayuno) {
        this.comeSoloDesayuno = comeSoloDesayuno;
    }
    public Date getHoraDesayuno() {
        return this.horaDesayuno;
    }
    
    public void setHoraDesayuno(Date horaDesayuno) {
        this.horaDesayuno = horaDesayuno;
    }
    public String getDesComida() {
        return this.desComida;
    }
    
    public void setDesComida(String desComida) {
        this.desComida = desComida;
    }
    public String getLugComida() {
        return this.lugComida;
    }
    
    public void setLugComida(String lugComida) {
        this.lugComida = lugComida;
    }
    public String getComeSoloComida() {
        return this.comeSoloComida;
    }
    
    public void setComeSoloComida(String comeSoloComida) {
        this.comeSoloComida = comeSoloComida;
    }
    public Date getHoraComida() {
        return this.horaComida;
    }
    
    public void setHoraComida(Date horaComida) {
        this.horaComida = horaComida;
    }
    public String getDesCena() {
        return this.desCena;
    }
    
    public void setDesCena(String desCena) {
        this.desCena = desCena;
    }
    public String getLugCena() {
        return this.lugCena;
    }
    
    public void setLugCena(String lugCena) {
        this.lugCena = lugCena;
    }
    public String getComeSoloCena() {
        return this.comeSoloCena;
    }
    
    public void setComeSoloCena(String comeSoloCena) {
        this.comeSoloCena = comeSoloCena;
    }
    public Date getHoraCena() {
        return this.horaCena;
    }
    
    public void setHoraCena(Date horaCena) {
        this.horaCena = horaCena;
    }




}


