package pojos;
// Generated 25/06/2012 06:37:10 PM by Hibernate Tools 3.2.1.GA



/**
 * ExpedienteDatos generated by hbm2java
 */
public class ExpedienteDatos  implements java.io.Serializable {


     private Integer idExpediente;
     private DatosPaciente datosPaciente;
     private Integer edaComObe;
     private String evtDisObe;
     private String tratPrev;
     private String medAct;
     private Double pesoInicial;
     private Double talla;
     private String estructuraOsea;
     private Double pesoIdeal;
     private Double cadera;
     private Double cintura;
     private Double busto;

    public ExpedienteDatos() {
    }

    public ExpedienteDatos(DatosPaciente datosPaciente, Integer edaComObe, String evtDisObe, String tratPrev, String medAct, Double pesoInicial, Double talla, String estructuraOsea, Double pesoIdeal, Double cadera, Double cintura, Double busto) {
       this.datosPaciente = datosPaciente;
       this.edaComObe = edaComObe;
       this.evtDisObe = evtDisObe;
       this.tratPrev = tratPrev;
       this.medAct = medAct;
       this.pesoInicial = pesoInicial;
       this.talla = talla;
       this.estructuraOsea = estructuraOsea;
       this.pesoIdeal = pesoIdeal;
       this.cadera = cadera;
       this.cintura = cintura;
       this.busto = busto;
    }
   
    public Integer getIdExpediente() {
        return this.idExpediente;
    }
    
    public void setIdExpediente(Integer idExpediente) {
        this.idExpediente = idExpediente;
    }
    public DatosPaciente getDatosPaciente() {
        return this.datosPaciente;
    }
    
    public void setDatosPaciente(DatosPaciente datosPaciente) {
        this.datosPaciente = datosPaciente;
    }
    public Integer getEdaComObe() {
        return this.edaComObe;
    }
    
    public void setEdaComObe(Integer edaComObe) {
        this.edaComObe = edaComObe;
    }
    public String getEvtDisObe() {
        return this.evtDisObe;
    }
    
    public void setEvtDisObe(String evtDisObe) {
        this.evtDisObe = evtDisObe;
    }
    public String getTratPrev() {
        return this.tratPrev;
    }
    
    public void setTratPrev(String tratPrev) {
        this.tratPrev = tratPrev;
    }
    public String getMedAct() {
        return this.medAct;
    }
    
    public void setMedAct(String medAct) {
        this.medAct = medAct;
    }
    public Double getPesoInicial() {
        return this.pesoInicial;
    }
    
    public void setPesoInicial(Double pesoInicial) {
        this.pesoInicial = pesoInicial;
    }
    public Double getTalla() {
        return this.talla;
    }
    
    public void setTalla(Double talla) {
        this.talla = talla;
    }
    public String getEstructuraOsea() {
        return this.estructuraOsea;
    }
    
    public void setEstructuraOsea(String estructuraOsea) {
        this.estructuraOsea = estructuraOsea;
    }
    public Double getPesoIdeal() {
        return this.pesoIdeal;
    }
    
    public void setPesoIdeal(Double pesoIdeal) {
        this.pesoIdeal = pesoIdeal;
    }
    public Double getCadera() {
        return this.cadera;
    }
    
    public void setCadera(Double cadera) {
        this.cadera = cadera;
    }
    public Double getCintura() {
        return this.cintura;
    }
    
    public void setCintura(Double cintura) {
        this.cintura = cintura;
    }
    public Double getBusto() {
        return this.busto;
    }
    
    public void setBusto(Double busto) {
        this.busto = busto;
    }




}


