package pojos;
// Generated 25/06/2012 06:37:10 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Receta generated by hbm2java
 */
public class Receta  implements java.io.Serializable {


     private Integer idReceta;
     private TipoReceta tipoReceta;
     private DatosPaciente datosPaciente;
     private String contenido;
     private Date fecha;

    public Receta() {
    }

    public Receta(TipoReceta tipoReceta, DatosPaciente datosPaciente, String contenido, Date fecha) {
       this.tipoReceta = tipoReceta;
       this.datosPaciente = datosPaciente;
       this.contenido = contenido;
       this.fecha = fecha;
    }
   
    public Integer getIdReceta() {
        return this.idReceta;
    }
    
    public void setIdReceta(Integer idReceta) {
        this.idReceta = idReceta;
    }
    public TipoReceta getTipoReceta() {
        return this.tipoReceta;
    }
    
    public void setTipoReceta(TipoReceta tipoReceta) {
        this.tipoReceta = tipoReceta;
    }
    public DatosPaciente getDatosPaciente() {
        return this.datosPaciente;
    }
    
    public void setDatosPaciente(DatosPaciente datosPaciente) {
        this.datosPaciente = datosPaciente;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


